### ISSUE TITLE
TypeError: Float cannot represent non numeric value: Invalid Date

### ISSUE THREAD

**Issue by joncursi** [tjmehta/graphql-date#12]
I'm getting this error and I have no idea why. I've been upgrading my graphql packages to keep up with the ecosystem and now getting this error on code that used to work.

Relevant package.json:

```
    "graphql": "0.10.5",
    "graphql-date": "^1.0.3",
    "graphql-loader": "^1.2.1",
    "graphql-log": "^0.1.3",
    "graphql-redis-subscriptions": "^1.2.0",
    "graphql-server-express": "^1.0.4",
    "graphql-subscriptions": "^0.4.4",
    "graphql-tools": "^1.0.0",
    "graphql-type-json": "^0.1.4",
```

**Comment by tjmehta** [comment]
cool I will check this out

**Comment by tjmehta** [comment]
can you send me a stack trace atleast or some repro code?

**Comment by joncursi** [comment]
This is the stack trace my server is logging to console:

```
W20170726-11:40:38.496(-4)? (STDERR) TypeError: Float cannot represent non numeric value: Invalid Date
W20170726-11:40:38.497(-4)? (STDERR)     at coerceFloat (/Users/jcursi/Sites/joncursi/redbird-web/node_modules/graphql/type/scalars.js:73:9)
W20170726-11:40:38.497(-4)? (STDERR)     at GraphQLScalarType.serialize (/Users/jcursi/Sites/joncursi/redbird-web/node_modules/graphql/type/definition.js:210:12)
W20170726-11:40:38.497(-4)? (STDERR)     at completeLeafValue (/Users/jcursi/Sites/joncursi/redbird-web/node_modules/graphql/execution/execute.js:668:37)
W20170726-11:40:38.498(-4)? (STDERR)     at completeValue (/Users/jcursi/Sites/joncursi/redbird-web/node_modules/graphql/execution/execute.js:617:12)
W20170726-11:40:38.498(-4)? (STDERR)     at completeValue (/Users/jcursi/Sites/joncursi/redbird-web/node_modules/graphql/execution/execute.js:597:21)
W20170726-11:40:38.499(-4)? (STDERR)     at completeValueWithLocatedError (/Users/jcursi/Sites/joncursi/redbird-web/node_modules/graphql/execution/execute.js:546:21)
W20170726-11:40:38.499(-4)? (STDERR)     at completeValueCatchingError (/Users/jcursi/Sites/joncursi/redbird-web/node_modules/graphql/execution/execute.js:515:12)
W20170726-11:40:38.500(-4)? (STDERR)     at resolveField (/Users/jcursi/Sites/joncursi/redbird-web/node_modules/graphql/execution/execute.js:467:10)
W20170726-11:40:38.500(-4)? (STDERR)     at /Users/jcursi/Sites/joncursi/redbird-web/node_modules/graphql/execution/execute.js:314:18
W20170726-11:40:38.506(-4)? (STDERR)     at Array.reduce (native)
```

**Comment by joncursi** [comment]
This appears to be an issue with the Meteor framework: https://github.com/orionsoft/meteor-apollo-accounts/issues/70
